global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'user-api'
    static_configs:
      - targets: ['user-api:3001']
  
  - job_name: 'vendor-api'
    static_configs:
      - targets: ['vendor-api:3002']
  
  - job_name: 'rider-api'
    static_configs:
      - targets: ['rider-api:3003']
  
  - job_name: 'admin-api'
    static_configs:
      - targets: ['admin-api:3005']
  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
